language: node_js
node_js:
  - 7
  
services:
  - docker

before_install: cd session-management
script:
  - echo "TODO - add unit test and integration tests"
after-success:
  - docker login -u $DOCKER_USER_NAME -p $DOCKER_PASSWORD
  - docker build -t $DOCKER_USER_NAME/captivate.session-management:$TRAVIS_COMMIT .
  - docker tag $DOCKER_USER_NAME/captivate.session-management:$TRAVIS_COMMIT $DOCKER_USER_NAME/captivate.session-management:latest
  - docker push $DOCKER_USER_NAME/captivate.session-management:latest
  - docker push $DOCKER_USER_NAME/captivate.session-management:$TRAVIS_COMMIT  
  - curl -X POST http://captivate:$JENKINS_USER_TOKEN@$JENKINS_URL/job/deploy_session_management/build?token=$JENKINS_JOB_TOKEN

branches:
  only:
    - deploy/session-management
